// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, user_id, amount, label, category, source, destination, created_at, updated_at)
VALUES(
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    now(),
    now()
)
RETURNING id, user_id, amount, label, category, source, destination, created_at, updated_at, deleted_at
`

type CreateTransactionParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Amount      int64     `json:"amount"`
	Label       string    `json:"label"`
	Category    string    `json:"category"`
	Source      string    `json:"source"`
	Destination string    `json:"destination"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Label,
		arg.Category,
		arg.Source,
		arg.Destination,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Label,
		&i.Category,
		&i.Source,
		&i.Destination,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAllTransactionsByUserID = `-- name: GetAllTransactionsByUserID :many
SELECT id, user_id, amount, label, category, source, destination, created_at, updated_at, deleted_at FROM transactions
WHERE user_id= $1
ORDER BY created_at ASC
`

func (q *Queries) GetAllTransactionsByUserID(ctx context.Context, userID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getAllTransactionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Label,
			&i.Category,
			&i.Source,
			&i.Destination,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, user_id, amount, label, category, source, destination, created_at, updated_at, deleted_at FROM transactions
WHERE id=$1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Label,
		&i.Category,
		&i.Source,
		&i.Destination,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
