// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, user_id, amount, label, category, source, destination, created_at, updated_at)
VALUES(
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    now(),
    now()
)
RETURNING id, user_id, amount, label, category, source, destination, created_at, updated_at, deleted_at
`

type CreateTransactionParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Amount      int64     `json:"amount"`
	Label       string    `json:"label"`
	Category    string    `json:"category"`
	Source      string    `json:"source"`
	Destination string    `json:"destination"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.UserID,
		arg.Amount,
		arg.Label,
		arg.Category,
		arg.Source,
		arg.Destination,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Label,
		&i.Category,
		&i.Source,
		&i.Destination,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTransactionByID = `-- name: DeleteTransactionByID :exec
UPDATE transactions
SET
    deleted_at=now()
WHERE id=$1
AND user_id=$2
AND deleted_at IS NULL
`

type DeleteTransactionByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTransactionByID(ctx context.Context, arg DeleteTransactionByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteTransactionByID, arg.ID, arg.UserID)
	return err
}

const getAllTransactionsByUserID = `-- name: GetAllTransactionsByUserID :many
SELECT id, user_id, amount, label, category, source, destination, created_at, updated_at, deleted_at FROM transactions
WHERE user_id= $1
AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetAllTransactionsByUserID(ctx context.Context, userID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getAllTransactionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Label,
			&i.Category,
			&i.Source,
			&i.Destination,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, user_id, amount, label, category, source, destination, created_at, updated_at, deleted_at FROM transactions
WHERE id=$1
AND user_id=$2
AND deleted_at IS NULL
`

type GetTransactionByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, arg GetTransactionByIDParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Label,
		&i.Category,
		&i.Source,
		&i.Destination,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserBalance = `-- name: GetUserBalance :one
SELECT  
    COALESCE(
        SUM(
            CASE 
                WHEN category = 'CREDIT' THEN amount
                WHEN category = 'DEBIT' THEN  -amount
            END
    ),
    0
)::BIGINT AS balance
FROM transactions
WHERE user_id=$1
AND deleted_at IS NULL
`

func (q *Queries) GetUserBalance(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserBalance, userID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const getUserExpenses = `-- name: GetUserExpenses :one
SELECT
COALESCE(SUM(amount), 0)::BIGINT AS total_expenses
FROM transactions
WHERE user_id=$1
AND category='DEBIT'
AND deleted_at IS NULL
`

func (q *Queries) GetUserExpenses(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserExpenses, userID)
	var total_expenses int64
	err := row.Scan(&total_expenses)
	return total_expenses, err
}

const getUserIncome = `-- name: GetUserIncome :one
SELECT 
    COALESCE(SUM(amount), 0) AS total_income
FROM transactions
WHERE user_id=$1
AND  category='CREDIT'
AND deleted_at IS NULL
`

func (q *Queries) GetUserIncome(ctx context.Context, userID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getUserIncome, userID)
	var total_income interface{}
	err := row.Scan(&total_income)
	return total_income, err
}

const updateTransactionByID = `-- name: UpdateTransactionByID :one
UPDATE transactions
SET 
    amount=$3,
    label=$4,
    category=$5,
    source=$6,
    destination=$7,
    updated_at=now()
WHERE id=$1
AND user_id=$2
AND deleted_at IS NULL
RETURNING id, user_id, amount, label, category, source, destination, created_at, updated_at, deleted_at
`

type UpdateTransactionByIDParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Amount      int64     `json:"amount"`
	Label       string    `json:"label"`
	Category    string    `json:"category"`
	Source      string    `json:"source"`
	Destination string    `json:"destination"`
}

func (q *Queries) UpdateTransactionByID(ctx context.Context, arg UpdateTransactionByIDParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransactionByID,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.Label,
		arg.Category,
		arg.Source,
		arg.Destination,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.Label,
		&i.Category,
		&i.Source,
		&i.Destination,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
